# Paracle Project Configuration
# Version: 0.0.1
# Schema: .parac v1.0

name: paracle-lite
version: 0.0.1
description: Framework multi-agent user-driven pour applications IA natives
schema_version: "1.0"

# Identity
identity:
  organization: IbIFACE-Tech
  repository: paracle-lite
  license: Apache-2.0
  homepage: https://github.com/IbIFACE-Tech/paracle-lite

# Team
team:
  maintainers:
    - role: lead
      contact: team@ibiface-tech.com

# Defaults
defaults:
  python_version: "3.10"
  agent_framework: internal # Will support msaf, langchain, llamaindex
  model_provider: openai
  default_model: gpt-4
  orchestrator: internal

# Project Metadata
metadata:
  created_at: "2025-12-24"
  phase: "Phase 0 - Foundation"
  status: active
  tags:
    - multi-agent
    - ai-framework
    - agent-inheritance
    - api-first

# Logging Configuration (Enterprise-grade)
# See: .parac/policies/LOG_MANAGEMENT.md for full policy
logging:
  # Global settings
  level: INFO # DEBUG, INFO, WARNING, ERROR, CRITICAL
  format: json # json (structured) or plain (text)

  # Centralized aggregation
  centralized:
    enabled: true
    type: local # local, elasticsearch, splunk, datadog
    endpoint: null # Set for external aggregators

  # Rotation strategy
  rotation:
    strategy: daily # daily, weekly, size-based
    backup_count: 30
    compression: true
    compress_after_days: 7

  # Retention policies (in days)
  retention:
    framework: 90 # ~/.paracle/logs/
    governance: null # .parac/memory/logs/ (permanent, versioned)
    runtime: 30 # .parac/memory/logs/runtime/
    security: 365 # Security events (compliance)
    errors: 90 # Error logs
    api_access: 180 # API access logs

  # Monitoring & Alerting
  monitoring:
    enabled: true
    error_threshold: 0.05 # 5% error rate alert
    disk_warning: 0.80 # 80% disk full warning
    disk_critical: 0.90 # 90% disk full critical

  alerting:
    enabled: false # Enable in production
    channels:
      email: []
      slack: null
      pagerduty: null

  # Security
  security:
    pii_redaction: true
    encrypt_at_rest: false # Future feature
    access_control: true
    audit_logging: true

  # Performance
  performance:
    async_logging: true
    batch_size: 100
    buffer_size_kb: 8
    rate_limit_per_second: 1000

  # Output targets
  output:
    console: true
    file: true
    aggregator: false # Set to true for external aggregators

  # Advanced features
  advanced:
    anomaly_detection: false # Future: ML-based detection
    log_correlation: true
    distributed_tracing: false # Future: OpenTelemetry

  # Compliance
  compliance:
    iso42001: true # AI Management
    iso27001: true # Information Security
    gdpr: true # Data Protection
    soc2: false # SOC 2 Type II
