---
# Simple sequential workflow
name: code-review
description: Automated code review workflow

steps:
  - id: analyze-code
    agent: code-analyzer
    input: |
      Analyze this code for:
      - Code quality
      - Best practices
      - Potential bugs

  - id: security-scan
    agent: security-scanner
    depends_on: [analyze-code]
    input: |
      Scan for security vulnerabilities:
      - SQL injection
      - XSS
      - Hardcoded secrets

  - id: generate-report
    agent: report-generator
    depends_on: [analyze-code, security-scan]
    input: |
      Generate report from:
      Analysis: {analyze-code.output}
      Security: {security-scan.output}

timeout: 300 # 5 minutes
