# Paracle Project Configuration (Minimal)
# Version: 0.1.0
# Schema: .parac v1.0
#
# This is the ESSENTIAL configuration - only what you need to get started.
# Optional advanced features are in separate config files (see below).

# ============================================
# ESSENTIAL CONFIGURATION
# ============================================

name: paracle-lite
version: 0.1.0
description: Framework multi-agent user-driven pour applications IA natives
schema_version: "1.0"

# Identity
identity:
  organization: IbIFACE-Tech
  repository: paracle-lite
  license: Apache-2.0
  homepage: https://github.com/IbIFACE-Tech/paracle-lite

# Team
team:
  maintainers:
    - role: lead
      contact: team@ibiface-tech.com

# LLM Defaults (MOST IMPORTANT - Edit these!)
defaults:
  python_version: "3.10"
  agent_framework: internal # Will support msaf, langchain, llamaindex
  model_provider: openai # openai, anthropic, google, groq, ollama
  default_model: gpt-4 # gpt-4, gpt-4o-mini, claude-3.5-sonnet, etc.
  orchestrator: internal

# Project Metadata
metadata:
  created_at: "2025-12-24"
  phase: "Phase 6 - Developer Experience"
  status: active
  tags:
    - multi-agent
    - ai-framework
    - agent-inheritance
    - api-first

# ============================================
# OPTIONAL CONFIGURATION FILES
# ============================================
# Load these only if you need advanced features.
# Comment out or remove lines to disable features.
#
# All paths relative to .parac/ directory.

include:
  # Logging configuration (enterprise-grade logging, rotation, retention)
  # See: .parac/config/logging.yaml
  - config/logging.yaml

  # Cost tracking & budgets (monitor LLM API costs, set spending limits)
  # See: .parac/config/cost-tracking.yaml
  - config/cost-tracking.yaml

  # File management (log limits, ADR templates, roadmap validation)
  # See: .parac/config/file-management.yaml
  - config/file-management.yaml
# ============================================
# QUICK START TIPS
# ============================================
#
# 1. Change model provider:
#    defaults.model_provider: "anthropic"
#    defaults.default_model: "claude-3.5-sonnet"
#
# 2. Disable optional features:
#    Comment out lines in 'include:' section above
#
# 3. Enable cost tracking:
#    Edit config/cost-tracking.yaml, set enabled: true
#
# 4. View full config:
#    paracle config show
#
# 5. Validate config:
#    paracle config validate
#
# Full documentation: docs/configuration-guide.md
